INSERT INTO Towns VALUES(1, 'Sofia')
INSERT INTO Towns VALUES(2, 'Plovdiv')
INSERT INTO Towns VALUES(3, 'Varna')
INSERT INTO Minions VALUES(1, 'Kevin', 22, 1)
INSERT INTO Minions VALUES(2, 'Bob', 15, 3)
INSERT INTO Minions VALUES(3, 'Steward', NULL, 2)